export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type CaseStatus = import('./workflow-types.ts').CaseStatus;

export interface Database {
  public: {
    Tables: {
      profiles: { Row: { id: string; email: string; display_name: string | null; role: 'customer' | 'staff' | 'admin'; mfa_enrolled_at: string | null; created_at: string }; Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at'> & { created_at?: string }; Update: Partial<Database['public']['Tables']['profiles']['Insert']>; Relationships: [] };
      organizations: { Row: { id: string; name: string; kind: 'owner' | 'agency'; created_at: string }; Insert: Omit<Database['public']['Tables']['organizations']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['organizations']['Insert']>; Relationships: [] };
      organization_members: { Row: { organization_id: string; user_id: string; role: 'owner' | 'member' | 'agency_admin'; created_at: string }; Insert: Omit<Database['public']['Tables']['organization_members']['Row'], 'created_at'> & { created_at?: string }; Update: Partial<Database['public']['Tables']['organization_members']['Insert']>; Relationships: [] };
      plans: { Row: { id: string; version: string; name: string; price_paise: number; billing: string; active: boolean; snapshot: Json; created_at: string }; Insert: Omit<Database['public']['Tables']['plans']['Row'], 'created_at'> & { created_at?: string }; Update: Partial<Database['public']['Tables']['plans']['Insert']>; Relationships: [] };
      orders: { Row: { id: string; organization_id: string; customer_user_id: string; plan_id: string; plan_version: string; quantity: number; subtotal_paise: number; gst_paise: number; total_paise: number; terms_version: string; payment_state: string; created_at: string }; Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['orders']['Insert']>; Relationships: [] };
      order_items: { Row: { id: string; order_id: string; site_id: string | null; quantity: number; plan_snapshot: Json; created_at: string }; Insert: Omit<Database['public']['Tables']['order_items']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['order_items']['Insert']>; Relationships: [] };
      payments: { Row: { id: string; order_id: string; provider: string; provider_transaction_id: string; state: string; amount_paise: number; webhook_fingerprint: string | null; verified_at: string | null; created_at: string }; Insert: Omit<Database['public']['Tables']['payments']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['payments']['Insert']>; Relationships: [] };
      subscriptions: { Row: { id: string; organization_id: string; order_id: string; provider_customer_ref: string | null; provider_mandate_ref: string | null; state: string; renews_at: string | null; created_at: string }; Insert: Omit<Database['public']['Tables']['subscriptions']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['subscriptions']['Insert']>; Relationships: [] };
      sites: { Row: { id: string; organization_id: string; order_id: string; url: string; access_state: string; created_at: string }; Insert: Omit<Database['public']['Tables']['sites']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['sites']['Insert']>; Relationships: [] };
      cases: { Row: { id: string; organization_id: string; order_id: string; site_id: string; status: CaseStatus; assigned_staff_id: string | null; payment_verified_at: string | null; access_usable_at: string | null; response_deadline_at: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['cases']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['cases']['Insert']>; Relationships: [] };
      case_events: { Row: { id: string; case_id: string; organization_id: string; type: string; from_status: CaseStatus | null; to_status: CaseStatus | null; body: string; customer_visible: boolean; actor_user_id: string; created_at: string }; Insert: Omit<Database['public']['Tables']['case_events']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: never; Relationships: [] };
      quotes: { Row: { id: string; case_id: string; organization_id: string; amount_paise: number; terms: string; state: string; accepted_at: string | null; created_at: string }; Insert: Omit<Database['public']['Tables']['quotes']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['quotes']['Insert']>; Relationships: [] };
      credential_sets: { Row: { id: string; case_id: string; organization_id: string; state: 'active' | 'revoked' | 'expired'; algorithm: 'aes-256-gcm'; nonce: string | null; auth_tag: string | null; ciphertext: string | null; key_version: string | null; created_at: string; expires_at: string | null; revoked_at: string | null; expired_at: string | null }; Insert: Omit<Database['public']['Tables']['credential_sets']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['credential_sets']['Insert']>; Relationships: [] };
      attachments: { Row: { id: string; case_id: string; organization_id: string; kind: string; storage_path: string; content_type: string; byte_size: number; customer_visible: boolean; scan_state: string; created_at: string }; Insert: Omit<Database['public']['Tables']['attachments']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['attachments']['Insert']>; Relationships: [] };
      webhook_events: { Row: { id: string; provider: string; fingerprint: string; payload_hash: string; received_at: string; processed_at: string | null }; Insert: Omit<Database['public']['Tables']['webhook_events']['Row'], 'id' | 'received_at'> & { id?: string; received_at?: string }; Update: Partial<Database['public']['Tables']['webhook_events']['Insert']>; Relationships: [] };
      audit_logs: { Row: { id: string; organization_id: string | null; actor_user_id: string | null; action: string; target_type: string; target_id: string | null; metadata: Json; created_at: string }; Insert: Omit<Database['public']['Tables']['audit_logs']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: never; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: {
      staff_assign_case: { Args: { p_case_id: string; p_staff_id: string }; Returns: Database['public']['Tables']['cases']['Row'] };
      staff_transition_case: { Args: { p_case_id: string; p_to_status: CaseStatus; p_body?: string }; Returns: Database['public']['Tables']['cases']['Row'] };
      staff_add_case_update: { Args: { p_case_id: string; p_body: string; p_customer_visible: boolean }; Returns: Database['public']['Tables']['case_events']['Row'] };
      staff_mark_access_usable: { Args: { p_case_id: string; p_access_usable_at?: string }; Returns: Database['public']['Tables']['cases']['Row'] };
      submit_credentials: { Args: { p_case_id: string; p_algorithm: string; p_key_version: string; p_nonce: string; p_auth_tag: string; p_ciphertext: string; p_expires_at?: string | null }; Returns: Json };
      revoke_credentials: { Args: { p_case_id: string; p_credential_set_id: string }; Returns: Json };
      reveal_credentials: { Args: { p_case_id: string; p_credential_set_id: string }; Returns: Json };
      purge_expired_credentials: { Args: { p_completed_before: string }; Returns: number };
      list_credentials_metadata: { Args: { p_case_id: string }; Returns: Array<{ id: string; case_id: string; organization_id: string; state: string; algorithm: string; key_version: string; created_at: string; expires_at: string | null; revoked_at: string | null; expired_at: string | null }> };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
